### ISSUE TITLE
NPE on pw help at console

### ISSUE THREAD

**Issue by SlimeDog** [PyroTempus/My-Plugins#29]
Spigot 1.13.2
PWP 2.1.1

At the console, execute
```
>pw help
[07:58:07 WARN]: Unexpected exception while parsing console command "pw help"
org.bukkit.command.CommandException: Unhandled exception executing command 'pw' in plugin PyroWeatherPro v2.1.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar-2018-11-06-1949:git-Spigot-2474d93-ca22de3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar-2018-11-06-1949:git-Spigot-2474d93-ca22de3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.2.jar-2018-11-06-1949:git-Spigot-2474d93-ca22de3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:684) [spigot-1.13.2.jar-2018-11-06-1949:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:459) [spigot-1.13.2.jar-2018-11-06-1949:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot-1.13.2.jar-2018-11-06-1949:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-11-06-1949:git-Spigot-2474d93-ca22de3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-11-06-1949:git-Spigot-2474d93-ca22de3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at me.arsmagica.Extra.CommandsMain.onCommand(CommandsMain.java:103) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar-2018-11-06-1949:git-Spigot-2474d93-ca22de3]
        ... 8 more
```

**Comment by PyroTempus** [comment]
Did you re-generate the config.yml file for the option to appear. It should appear as:

`  Other:
    RemoveEmptyLines: true`

**Comment by PyroTempus** [comment]
Nevermind, found the error, will fix now.

**Comment by SlimeDog** [comment]
```
Did you re-generate the config.yml file for the option to appear. It should appear as:
Other: RemoveEmptyLines: true
```
Yes.
