### ISSUE TITLE
Blocking I/O operation on reload

### ISSUE THREAD

**Issue by SlimeDog** [PyroTempus/My-Plugins#39]
Spigot 1.13.2 latest
PyroWeatherPro 3.0.1

Not always, but frequently:
```
>pw reload
[18:35:33 INFO]: [PyroWeatherPro] Disabling PyroWeatherPro v3.0.1
[18:35:33 INFO]: [PyroWeatherPro] Enabling PyroWeatherPro v3.0.1
[18:35:33 WARN]: Enabled plugin with unregistered PluginClassLoader PyroWeatherPro v3.0.1
[18:35:33 WARN]: [LagMonitor] Plugin PyroWeatherPro is performing a blocking I/O operation (Socket: https://api.spigotmc.org/legacy/premium.php?user_id=56363&resource_id=60394&nonce=1065363634) on the main thread. This could affect the server performance, because the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Keep in mind to keep the code thread-safe. Report it to the plugin author
[18:35:33 WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developer to find the source. LagMonitor doesn't prevent this action. It just warns you about it. 
java.lang.IllegalAccessException: null
        at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:62) [LagMonitor-1.17.1-b152.jar:?]
        at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:48) [LagMonitor-1.17.1-b152.jar:?]
        at com.github.games647.lagmonitor.listener.BlockingConnectionSelector.select(BlockingConnectionSelector.java:30) [LagMonitor-1.17.1-b152.jar:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1175) [?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1065) [?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1063) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:793) [?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1062) [?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) [?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581) [?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1501) [?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1499) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:793) [?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) [?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245) [?:?]
        at me.arsmagica.PyroWeather.loadConfig0(PyroWeather.java) [PyroWeatherPro-3.0.1.jar:?]
        at me.arsmagica.PyroWeather.onEnable(PyroWeather.java) [PyroWeatherPro-3.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at me.arsmagica.Extra.CommandsMain.onCommand(CommandsMain.java:318) [PyroWeatherPro-3.0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:689) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:459) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar-2019-02-26-0112:git-Spigot-4165cd8-40cbae4]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by PyroTempus** [comment]
Duplicate + Fixed.
